contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: 66d300ee-1107-4e2e-8123-ba8cfc72aa8e
inputs: []
name: Playbook Last Final paling akhir no fek riil
outputs: []
quiet: true
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: ab0b8463-ef06-45a8-8228-3e78bdb6f70a
      iscommand: false
      name: ""
      version: -1
    taskid: ab0b8463-ef06-45a8-8228-3e78bdb6f70a
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 65,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
