contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: b0c7c298-4f30-4b61-8043-1ca8dfdddf67
inputs: []
name: sample
outputs: []
quiet: true
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: a623b3f2-e00a-408b-8e60-8d4b72e2404a
      iscommand: false
      name: ""
      version: -1
    taskid: a623b3f2-e00a-408b-8e60-8d4b72e2404a
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 65,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
