contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: 1447ae84-ed8e-455a-82fe-55a61b38bdd5
inputs: []
name: No action
outputs: []
quiet: true
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: f07cffd7-c176-427d-8042-2f464855d48f
      iscommand: false
      name: ""
      version: -1
    taskid: f07cffd7-c176-427d-8042-2f464855d48f
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 65,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
