contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: acfd8fd9-6af8-4134-8692-7eaa068247bf
inputs: []
name: Mazaya_Generator_Incident_10000
outputs: []
quiet: true
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: ae1367fc-e4de-4178-8926-07636a8c5932
      iscommand: false
      name: ""
      version: -1
    taskid: ae1367fc-e4de-4178-8926-07636a8c5932
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 65,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
